### ISSUE TITLE
Request: Allow non-mod users to "/check closed" for their own tickets

### ISSUE THREAD

**Issue by jakelauer** [ProjectInfinity/ReportRTS#27]
A problem we often have with our players is that they are unaware that their ticket has been closed, so they simply file another one. This can happen 3 or 4 times before a user finally sees that their ticket has been answered and what the answer was. If they could check the closed items, it'd be EXTREMELY helpful.

Thanks :)

**Comment by ProjectInfinity** [comment]
Currently implementing this.
