### ISSUE TITLE
Add Messaging-System

### ISSUE THREAD

**Issue by Trikolon** [ProjectInfinity/ReportRTS#52]
I would like to have a mail-system included in the plugin (Offline-msg support).
Staff should be able to communicate with a player even though a ticket is still opened. Messages should be assigned to tickets and should be visible in a tickets history.

Command-suggestions:
/ticket msg [id] [msg] => Send a message to the ticket-creator
/ticket read [id] => Shows message history as well?

**Comment by ProjectInfinity** [comment]
Started work on this in #57.
