### ISSUE TITLE
Request: Using ReportRTS without MySQL?

### ISSUE THREAD

**Issue by Vizitri** [ProjectInfinity/ReportRTS#56]
Is there a way to do this? I'd love to use it for my server, but I don't have a MySQL database. If there is a way to do this and I'm just being an idiot, please tell me. If not, I'd love to see this option added. :)

**Comment by ProjectInfinity** [comment]
There is currently no way to do this.

**Comment by Vizitri** [comment]
Okay

**Comment by SuperSpyTX** [comment]
![](http://i.imgur.com/42G7fd8.jpg)
