### ISSUE TITLE
/comment command

### ISSUE THREAD

**Issue by Vidsify** [ProjectInfinity/ReportRTS#57]
Is it possible you could add a /comment command for other staff members to comment on a modreq.

**Comment by ProjectInfinity** [comment]
Comments are something I have been thinking about for a while and it is the most opportune moment right now with all the rewrites. It may or may not come, no clue just yet.

**Comment by Vidsify** [comment]
It would be great if it could be added because I work for a network and we get a lot of reports from our players saying things like 'This guy came on a started swearing' it would be nice to comment on their modreq like /comment <id> Please can you comment back with the players name. So the staff member who is handling can comment and so can the player.

Also this is nothing to do with a comment command but when staff member do /hold <id> can they stay in the /check please like when a staff member does /claim <id> it says Claimed by <player> but /hold saying Help by <player>

**Comment by ProjectInfinity** [comment]
Backend and creation of comments are now in place in build 38 (http://ci.regularbox.com/job/ReportRTS/38/).

Still working on tying them into /ticket read in an as elegant way as possible.

**Comment by ProjectInfinity** [comment]
Added TicketCommentEvent.

**Comment by Vidsify** [comment]
Awesome thank you! :+1:

**Comment by ProjectInfinity** [comment]
![comment](http://i.imgur.com/tVnGk5b.png)

Found a bug though, only one comment seem to be displayed even if there are more... :-1:  Will continue work after I sleep.

**Comment by ProjectInfinity** [comment]
![comment](http://i.imgur.com/WWHTmnc.png)

**Comment by ProjectInfinity** [comment]
I have now resolved most if not any problem I have encountered while creating the comment system. Should be okay to test on a test server. Do remember that the latest builds of ReportRTS are VASTLY different than the ones found on BukkitDev. 

**BACKUP YOUR DATA.**

**Comment by Vidsify** [comment]
@ProjectInfinity Has this been released fully yet?

**Comment by ProjectInfinity** [comment]
Released no, in development builds? Yes.

**Comment by Vidsify** [comment]
@ProjectInfinity Ok thank you. Do you have an ETA on release?

**Comment by ProjectInfinity** [comment]
No.

**Comment by Vidsify** [comment]
Ok
