### ISSUE TITLE
Please change utf8mb4 to utf8

### ISSUE THREAD

**Issue by dzmen** [ProjectInfinity/ReportRTS#58]
A lot of server hosts are still using mysql 5.1. That means it doesnt support utf8mb4 so I can't run your plugin. Could you maybe change it or add mysql 5.1 support :)?

Thank you.

**Comment by ProjectInfinity** [comment]
A lot of server hosts? ReportRTS is not made for shared hosting, it is made for people running VPS' and dedicated servers. However, if you have database access you can manually alter the tables.

Tell your host to upgrade to at least MySQL 5.5 though, 5.1 is end of life as of December 31st 2013.

**Comment by comniemeer** [comment]
I have to agree with dzmen, in CentOS, MySQL is still on 5.1.73...
Installing via alternative packet sources is very complicated.

**Comment by ProjectInfinity** [comment]
@comniemeer http://www.tecmint.com/enable-rpmforge-repository/

5.5 is required. 5.1 doesn't support mb4 which is required for certain languages. To workaround you can simply edit the encoding yourself.
