### ISSUE TITLE
messages.yml being re-written every server reboot

### ISSUE THREAD

**Issue by seriosbrad** [ProjectInfinity/ReportRTS#59]
Running: http://ci.regularbox.com/job/ReportRTS/33/

Upon server reboot, messages.yml is re-written with the default config.  If I chmod the file so that no write access it allowed, it keeps my settings.

While I'm here, would you consider converting to a more simple color code formatting using the ampersand codes?  (&).  Thanks!

**Comment by ProjectInfinity** [comment]
Don't use builds past 8. Messages are being completely rewritten.
