### ISSUE TITLE
MySQL Syntax Error on closing ticket

### ISSUE THREAD

**Issue by Puremin0rez** [ProjectInfinity/ReportRTS#63]
Upgraded from a few month old build on an existing database and am presented with the following error whenever attempting to close a ticket.

http://pastebin.com/Y6uXf2PN

I'm able to comment on the ticket and people are able to submit them, but I cannot close them.

**Comment by ProjectInfinity** [comment]
In the ticket table, is the comment column present?

**Comment by Puremin0rez** [comment]
It does not appear to be.
https://puremin0rez.me/images/XxPYE_04-07-2015.png

**Comment by SuperSpyTX** [comment]
Based on my initial review of the code, the data schema (in the upgrade/migration code) doesn't add the 'comment' column when when the database gets upgraded.

It looks like if your version of the database had its predecessor (reportrts_requests), it gets fixed here:
https://github.com/ProjectInfinity/ReportRTS/blob/master/src/main/java/com/nyancraft/reportrts/persistence/MySQLDataProvider.java#L226

But not when the database gets created:
https://github.com/ProjectInfinity/ReportRTS/blob/master/src/main/java/com/nyancraft/reportrts/persistence/MySQLDataProvider.java#L248

And then it's assumed it exists here (and in other spots, but this is related to this issue):
https://github.com/ProjectInfinity/ReportRTS/blob/master/src/main/java/com/nyancraft/reportrts/persistence/MySQLDataProvider.java#L1120

**Comment by ProjectInfinity** [comment]
That's what I thought, thanks for pointing it out though, I'll look at it further after a good night's sleep.

**Comment by SuperSpyTX** [comment]
Do you think maybe its simple enough for a pull request?

**Comment by ProjectInfinity** [comment]
@SuperSpyTX I can take care of it. The thing is that there are some remains left of the comment column, it's now obsolete as there's an entire table dedicated to comments thanks to the new comment system. Just gotta remove it.

**Comment by ProjectInfinity** [comment]
@Puremin0rez let me know if that covers it.
http://ci.regularbox.com/job/ReportRTS/52/

**Comment by Puremin0rez** [comment]
@ProjectInfinity All good now :)
