### ISSUE TITLE
Error onCommand

### ISSUE THREAD

**Issue by v3Monsta** [ProjectInfinity/ReportRTS#64]
http://pastebin.com/rQEUaQue

**Comment by ProjectInfinity** [comment]
Which build?

**Comment by ProjectInfinity** [comment]
Stats doesn't take an argument anymore. /rts stats, it then shows you the top 10 staff members, ordered by most resolved tickets.

It shouldn't cause that error even if you specified a target as can be seen here:
![http://i.imgur.com/5fXm9UN.png](http://i.imgur.com/5fXm9UN.png)


Have you modified your build of ReportRTS?

**Comment by v3Monsta** [comment]
No I haven't modified the build of ReportRTS(v1.2.2). I'm also using Spigot 1.8.3, I tried downgrading to Spigot 1.8, but I still got the same error using the command "/rts stats {player}".
http://pastebin.com/6GCwc4fF

I also got another error when I tried to close the server. Commands used: {/save-all} -> {/stop}
http://pastebin.com/x6c8T2ZL

**Comment by ProjectInfinity** [comment]
@v3Monsta see your pastes. ReportRTS v1.2.2-b194
That is a pretty old build. You are not running build 52.
http://ci.regularbox.com/job/ReportRTS/

**Comment by v3Monsta** [comment]
My mistake. I updated my build but I still get the same error when I used {/rts stats}
http://pastebin.com/zLKE2esT

I also got this error when I tried to shut down the server.
http://pastebin.com/TBNFaMgC

**Comment by ProjectInfinity** [comment]
Look at your startup, it seems like your mysql connection info is wrong.

**Comment by v3Monsta** [comment]
I set the database up again and got this error message
http://pastebin.com/C9SHpUFG

**Comment by ProjectInfinity** [comment]
You are restarting per try right? Do **not** do /rts reload after changing MySQL information.

Can you show me all of your startup logs? I can see that it does

**Comment by v3Monsta** [comment]
I actually didn't know I couldn't use /rts reload to reload MySQL information, I restarted the server fully and everything seems to work fine. Sorry :/.
