### ISSUE TITLE
/check causes some kind of exception in the latest dev build

### ISSUE THREAD

**Issue by Islid** [ProjectInfinity/ReportRTS#66]
Versions:

ReportRTS: 2.0.0-b52
Spigot: git-Spigot-44c59bf-8f0f4ed (MC 1.8.7 Implementation) (API 1.8.7-R0.1-SNAPSHOT)

Issue:

An exception is generated upon using the /check command by itself, with no variables included. When variables (like an ID number for a ticket) are used, the problem doesn't occur.

Pastebin of error: http://pastebin.com/vZUT5bTU
Pastebin of config: http://pastebin.com/N135JN4r

Any thoughts?

**Comment by ProjectInfinity** [comment]
Either turn fancy rickets off in the configuration or install protocollib.

**Comment by Islid** [comment]
Installing the latest version of ProtocolLib (3.6.3-SNAPSHOT-b134) and disabling the fancy option does seem to have fixed the issue, at least as far as we can tell from a few hours of testing. Is there a way to make it so we can turn the fancy option back on?

**Comment by ProjectInfinity** [comment]
As long as you have a working ProtocolLib installed, you should be able 
to have it on.

**Comment by Islid** [comment]
Alright, testing that now...

**Comment by Islid** [comment]
The problem seems to be resolved. Thanks for the info!
