### ISSUE TITLE
Crash on Start Up - "Unknown Character Set 'utf8mb4'"

### ISSUE THREAD

**Issue by Murreey** [ProjectInfinity/ReportRTS#69]
I'm getting a MySQLException when ReportRTS tries to start when the server boots. It's the first time I've updated ReportRTS in a while so I'm not sure if something went wrong in the database conversion.

Running ReportRTS 2.0.0-b52 (latest), Spigot git-Spigot-fdc1440-53fac9f (MC: 1.8.8) 

Error log: https://gist.github.com/Murreey/4c6fbfeccfe822f4040a

Thanks!

**Comment by ProjectInfinity** [comment]
Your mysql server is severely out of date. You have to update it.

**Comment by Murreey** [comment]
Do you know which version I'd have to use? We're currently running 5.1.73 but I'm not sure we have access to change that, as it's a hosted solution.

**Comment by ProjectInfinity** [comment]
5.1 is not even supported by oracle anymore if I recall correctly. Time to upgrade. Let your host know if it can't be changed.
