### ISSUE TITLE
MySQLSyntaxError

### ISSUE THREAD

**Issue by v3Monsta** [ProjectInfinity/ReportRTS#71]
After filling out the info to connect to the db, I tried to enable the plugin but this error pops up and then disables the plugin. I checked the db and no tables were created.

http://hastebin.com/imabibipap.avrasm

OS: Ubuntu Server 16.04
MySQL version: 5.7.12

**Comment by ProjectInfinity** [comment]
Ahhh, it's a MySQL 5.7 issue it seems like. Do you have another version you can use until this is fixed?

**Comment by v3Monsta** [comment]
I don't, however I am in no rush to have this fixed as the server is still under development.

**Comment by ProjectInfinity** [comment]
Fixed in https://github.com/ProjectInfinity/ReportRTS/commit/8486649bb4cf0501c9994e32cd3b17e403a63a16
